openapi: "3.0.2"

info:
  title: API for bachelor project
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9

paths:
  /signup:
    post:
      tags:
        - Auth
      operationId: Signup
      description: Зарегистрироваться

      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              description: Регистрационные данные
              properties:
                username:
                  type: string
                  description: Логин
                first_name:
                  type: string
                  description: Имя
                middle_name:
                  type: string
                  description: Отчество
                last_name:
                  type: string
                  description: Фамилия
                phone:
                  type: string
                  description: Номер телефона
                email:
                  type: string
                  description: Адрес электронной почты
                birth_date:
                  type: string
                  format: date
                  description: Дата рождения
                password:
                  type: string
                  format: password
                  description: Хеш пароля

      responses:
        '200':
          description: Успех
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    description: Результат
                    enum:
                      - success
                  message:
                    type: string
                    enum:
                      - null

        '400':
          description: Ошибка
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    description: Результат
                    enum:
                      - error
                  message:
                    type: string
                    description: Описание ошибки

        '403':
          description: Доступ запрещён

        '500':
          description: Внутренняя ошибка сервера

  /login:
    post:
      tags:
        - Auth
      operationId: Login
      description: Вход в систему

      requestBody:
        required: true
        description: Данные для авторизации

       responses:
        '200':
          description: Успех

        '400':
          description: Ошибка

        '403':
          description: Доступ запрещён

        '500':
          description: Внутренняя ошибка сервера
       
  /logout:
    post:
      tags:
        - Auth
      description: Выход из системы

      responses:
        '200':
          description: Успех

        '400':
          description: Ошибка

        '401':
          description: Пользователь не авторизован

        '403':
          description: Доступ запрещён

        '500':
          description: Внутренняя ошибка сервера
