openapi: "3.0.2"

info:
  title: API for bachelor project
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9

paths:
  /api/get-notifications-count:
    get:
      tags:
        - Notifications
      operationId: Get notifications count
      description: Получить количество непрочитанных уведомлений

      responses:
        '200':
          description: Количество непрочитанных уведомлений
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    description: Количество непрочитанных уведомлений
        
        '400':
          description: Ошибка

        '401':
          description: Пользователь не авторизован

        '403':
          description: Доступ запрещён

        '500':
          description: Внутренняя ошибка сервера

  /api/get-notifications:
    get:
      tags:
        - Notifications

      operationId: Get notifications
      description: Получить уведомления
      parameters:
        - name: offset
          in: query
          schema:
            type: integer
            minimum: 0
            default: 0
          required: false
          description: Смещение от начала
        - name: limit
          in: query
          schema:
            type: integer
            minimum: 1
            default: 10
          required: false
          description: Количество

      responses:
        '200':
          description: Уведомления
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      format: uuid
                      description: ID уведомления
                    title:
                      type: string
                      description: Название
                    text:
                      type: string
                      description: Текст уведомления
                    date:
                      type: string
                      format: date
                      description: Дата уведомления
                    is_read:
                      type: boolean
                      description: Прочитано

        '400':
          description: Ошибка

        '401':
          description: Пользователь не авторизован

        '403':
          description: Доступ запрещён

        '500':
          description: Внутренняя ошибка сервера
        
  /api/set-notification-read:
    post:
      tags:
        - Notifications
      operationId: Set notification read
      description: Пометить уведомление как прочитанное

      requestBody:
        required: true
        content:
          applicaton/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  format: uuid
                  description: ID уведомления

      responses:
        '200':
          description: Успех
        
        '400':
          description: Ошибка

        '401':
          description: Пользователь не авторизован

        '403':
          description: Доступ запрещён

        '500':
          description: Внутренняя ошибка сервера      
